[theme]
# Primary colors for dark theme
primaryColor = "#2E86AB"           # Blue accent color for buttons and highlights
backgroundColor = "#0E1117"        # Dark background color
secondaryBackgroundColor = "#262730" # Slightly lighter dark for containers
textColor = "#FAFAFA"              # Light text for readability

# Font configuration
font = "sans serif"                # Clean, modern font

# UI behavior
base = "dark"                      # Force dark theme

[server]
# Performance optimizations
maxUploadSize = 200                # MB
maxMessageSize = 200               # MB
enableCORS = false
enableXsrfProtection = true

# Development settings
runOnSave = true
allowRunOnSave = true

[browser]
# Streamlit Cloud and browser behavior
gatherUsageStats = false
showErrorDetails = true

[logger]
# Logging configuration for development
level = "info"

[client]
# Client-side optimizations
caching = true
displayEnabled = true
showErrorDetails = true

# Toolbar configuration to minimize UI clutter
toolbarMode = "minimal"

[ui]
# Hide certain UI elements for cleaner look
hideTopBar = false
hideSidebarNav = false

# Development mode settings
[global]
# Development features
developmentMode = true
showWarningOnDirectExecution = false

# Metrics and analytics
disableWatchdogWarning = true
suppressDeprecationWarnings = true

# Memory management
maxCachedMessageAge = 3600          # 1 hour in seconds
